### ISSUE TITLE
已经无法使用,应该是逻辑问题,爱企查的查询逻辑改变,resultlist总是空的

### ISSUE THREAD

**Issue by shanfenglan** [wgpsec/ENScan#13]
<img width="517" alt="image" src="https://user-images.githubusercontent.com/49781523/154627546-d35e59fc-439f-4263-b082-5701d1bf7f41.png">
<img width="765" alt="image" src="https://user-images.githubusercontent.com/49781523/154627620-4841722a-405a-4f90-9028-6cafc2a4b886.png">

**Comment by flyballon** [comment]
【风险校验】需要更新Cookie https://aiqicha.baidu.com/s?q= 我是这样子

**Comment by keac** [comment]
已修复，建议使用ENScanGo
