### ISSUE TITLE
功能建议: 获取到公司的控股公司信息后的一些信息查询

### ISSUE THREAD

**Issue by s1g0day** [wgpsec/ENScan#17]
架构：上游控股公司<--- 目标公司 --->下游控股公司
控股比例：百分百控股、xxx控股
行为：
1、在获取到目标公司的上下游控股公司信息后根据控股比例要求提取相关公司域名(默认百分百控股最有价值)
2、根据域名反查备案
3、再根据备案进行反查域名，进而获取到整个链上所有相关域名

这个功能若实现，何愁一个个手工检索控股公司域名

可惜目前go菜，暂时没法提供代码了

**Comment by keac** [comment]
这个想法在GO的版本中已经实现了，在[releases](https://github.com/wgpsec/ENScan_GO/releases)中可以下载 不知道师傅说的
1. 是否是查控股的子公司（已经实现，支持多级），还是股东公司？
2. 域名反查备案这个没有太理解，基本上是根据公司名字来查公司的备案，所以域名反查备案不知道有什么实际应用场景？如果需要可能得单独加一个入口查询
3. 目前已经支持备案查域名，但是后面没有理解是什么意思，另外python版本的应该也是支持占股公司信息查询的

**Comment by s1g0day** [comment]
1、第一条是目标公司的股东公司及控股公司，也就是打不动子公司就尝试母公司。
2、第二三条原本想法是根据域名查询公司，然后根据公司备案查询所有域名信息，经过师傅这样描述才发现我这个描述是有问题的，直接查询公司下所有备案域名就好了

但是我浅薄了，才发现用的还是ENScan而不是ENScan_GO

**Comment by keac** [comment]
> 1、第一条是目标公司的股东公司及控股公司，也就是打不动子公司就尝试母公司。 2、第二三条原本想法是根据域名查询公司，然后根据公司备案查询所有域名信息，经过师傅这样描述才发现我这个描述是有问题的，直接查询公司下所有备案域名就好了
> 
> 但是我浅薄了，才发现用的还是ENScan而不是ENScan_GO

针对这其中的第一条，针对股东公司的收集还没有看到师傅有提需求，但是在查询投资公司的时候会自动带出股东信息
