### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Wnltc** [wgpsec/ENScan#6]
大佬,能不能把微博、公众号、软件著作这部分的内容也一并导出呢

**Comment by keac** [comment]
@Wnltc 懒得写 哈哈哈哈

**Comment by keac** [comment]
@Wnltc 这个可以，平常用到多么

**Comment by Wnltc** [comment]
> @Wnltc 这个可以，平常用到多么

还行,常规项目跟红队项目都有收集公众号跟app的需求
